### ISSUE TITLE
Handle missing files

### ISSUE THREAD

**Issue by janpio** [williamluke4/prisma-viewer#4]
Right now missing files are not recognized and you get an error like this:

```
λ pv
Error: Error: Schema parsing
error: Unexpected token. Expected one of: datamodel declaration
  -->  schema.prisma:1
   |
   |
 1 | undefined
   | ^ Unexpected token.
   |

Validation Error Count: 1
    at Object.<anonymous> (C:\ProgramData\nvm\v12.6.0\node_modules\prisma-viewer\node_modules\@prisma\sdk\dist\engineCommands.js:128:23)
    at Generator.throw (<anonymous>)
    at rejected (C:\ProgramData\nvm\v12.6.0\node_modules\prisma-viewer\node_modules\@prisma\sdk\dist\engineCommands.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

```

Problem here is not that `schema.prisma` includes `undefined`, but that the the file seem to be missing.

**Comment by williamluke4** [comment]
This should be fixed in 1.0.4
